---

- name: Clone the git repository associated with the django project
  git:
    repo: "{{ django_project_repo_url }}"
    version: "{{ django_project_repo_version }}"
    dest: "{{ django_project_path }}"
    accept_hostkey: yes
    recursive: no
    force: yes
    key_file: "{{ deploy_key_filepath|default('') }}"
