---

- include: system.yml
- include: db.yml
  when: django_db_managed

- block:
  - include: git.yml
  - include: virtualenv.yml
  - include: jsonsettings.yml
  - include: node_assets.yml
    when: django_node_assets_enabled
  - include: django.yml
    when: django_commands_enabled

  become: yes
  become_user: "{{ django_user }}"

- include: uwsgi.yml
- include: nginx.yml
