---

- name: Ensure that the Django project's user exists and is in the www-data group
  user:
    name: "{{ django_user }}"
    createhome: yes
    shell: /bin/bash
    append: yes
    groups: www-data
    generate_ssh_key: yes

- name: Ensure that our base project path has proper permissions
  file:
    path: "{{ django_path }}"
    state: directory
    owner: "{{ django_user }}"
    group: www-data
    mode: ug=rwx,o=

- block:
  - set_fact:
      deploy_key_filepath: "/home/{{ django_user }}/.ssh/deploy_key"

  - name: Send private deploy key to the remote project's user if applicable
    copy:
      src: "{{ django_deploy_key_filepath }}"
      dest: "{{ deploy_key_filepath }}"
      owner: "{{ django_user }}"
      mode: 0600

  when: "django_deploy_key_filepath != ''"

- name: Install additional packages that could be required by the Django app
  apt:
    state: present
    name:
      - gettext
      - python3-venv
      - uwsgi
      - uwsgi-plugin-python
      - uwsgi-plugin-python3
      - uwsgi-src
      - uuid-dev
      - libcap-dev
      - libpcre3-dev

- name: Add Python's deadsnakes repository
  apt_repository: repo="ppa:deadsnakes/ppa"

- name: Install the python version required for the Django application
  apt:
    state: present
    name:
      - "{{ django_python_version }}"
      - "{{ django_python_version }}-dev"
      - "{{ django_python_version }}-venv"

- name: Ensure that the required folders exist
  file: path={{ item }} state=directory owner={{ django_user }}
  with_items:
    - "{{ django_path }}"
    - "{{ django_static_path }}"
    - "{{ django_media_path }}"
