---

- name: Ensure that the Django project's user exists and is in the www-data group
  user:
    name: "{{ django_user }}"
    createhome: no
    shell: /bin/bash
    append: yes
    groups: www-data

- name: Ensure that our base project path has proper permissions
  file:
    path: "{{ django_path }}"
    state: directory
    owner: "{{ django_user }}"
    group: www-data
    mode: ug=rwx,o=

- name: Install additional packages that could be required by the Django app
  apt: name={{ item }} state=present
  with_items:
    - gettext
    - libav-tools
    - libjpeg-dev
    - libpng12-dev
    - python3-venv
    - python-software-properties
    - uwsgi
    - uwsgi-plugin-python
    - uwsgi-plugin-python3

- name: Add Python's deadsnakes repository
  apt_repository: repo="ppa:fkrull/deadsnakes"

- name: Install the python version required for the Django application
  apt: name="{{ item }}" state=present
  with_items:
    - "{{ django_python_version }}"
    - "{{ django_python_version }}-dev"

- name: Ensure that the required folders exist
  file: path={{ item }} state=directory owner={{ django_user }}
  with_items:
    - "{{ django_path }}"
    - "{{ django_static_path }}"
    - "{{ django_media_path }}"
